# Generated by Django 4.2.20 on 2025-03-23 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsRawMaterials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RawMaterialBatchCode', models.CharField(blank=True, max_length=50, unique=True)),
                ('RawMaterialName', models.CharField(max_length=255)),
                ('DateDelivered', models.DateField()),
                ('QuantityBought', models.IntegerField(default=0)),
                ('QuantityLeft', models.IntegerField(default=0)),
                ('UseCategory', models.CharField(choices=[('WBC', 'WBC'), ('GGB', 'GGB'), ('Both', 'Both')], default='GGB', max_length=10)),
                ('ExpirationDate', models.DateField()),
                ('Status', models.CharField(blank=True, max_length=15)),
                ('Cost', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingRawMaterials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PackagingBatchCode', models.CharField(blank=True, max_length=50, unique=True)),
                ('RawMaterialName', models.CharField(max_length=255)),
                ('QuantityBought', models.IntegerField(default=0)),
                ('QuantityLeft', models.IntegerField(default=0)),
                ('UseCategory', models.CharField(choices=[('WBC', 'WBC'), ('GGB', 'GGB'), ('Both', 'Both')], max_length=10)),
                ('Status', models.CharField(blank=True, max_length=15)),
                ('Cost', models.IntegerField(blank=True, default=0, null=True)),
                ('ContainerSize', models.CharField(blank=True, max_length=50, null=True)),
                ('DateDelivered', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierCode', models.CharField(help_text='Unique identifier for the supplier (manually given).', max_length=50, primary_key=True, serialize=False)),
                ('SupplierName', models.CharField(max_length=255)),
                ('Category', models.CharField(choices=[('Ingredient', 'Ingredient'), ('Packaging', 'Packaging'), ('Both', 'Both')], max_length=10)),
                ('SocialMedia', models.CharField(blank=True, max_length=255, null=True)),
                ('EmailAddress', models.CharField(blank=True, max_length=320, null=True)),
                ('ContactNumber', models.CharField(blank=True, max_length=18, null=True)),
                ('PointPerson', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsedPackaging',
            fields=[
                ('USEDPackagingBatchCode', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('RawMaterialName', models.CharField(max_length=255)),
                ('QuanityUsed', models.IntegerField()),
                ('UseCategory', models.CharField(choices=[('WBC', 'WBC'), ('GGB', 'GGB'), ('Both', 'Both')], max_length=10)),
                ('DateUsed', models.DateField()),
                ('PackagingRawMaterialBatchCode', models.ForeignKey(db_column='PackagingBatchCode', on_delete=django.db.models.deletion.CASCADE, to='IMAPS_app.packagingrawmaterials')),
            ],
        ),
        migrations.CreateModel(
            name='UsedIngredient',
            fields=[
                ('UsedIngredientBatchCode', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('RawMaterialName', models.CharField(max_length=255)),
                ('QuantityUsed', models.IntegerField()),
                ('UseCategory', models.CharField(choices=[('WBC', 'WBC'), ('GGB', 'GGB'), ('Both', 'Both')], max_length=10)),
                ('DateUsed', models.DateField()),
                ('IngredientRawMaterialBatchCode', models.ForeignKey(db_column='RawMaterialBatchCode', on_delete=django.db.models.deletion.CASCADE, to='IMAPS_app.ingredientsrawmaterials')),
            ],
        ),
        migrations.AddField(
            model_name='packagingrawmaterials',
            name='SupplierCode',
            field=models.ForeignKey(db_column='SupplierCode', on_delete=django.db.models.deletion.CASCADE, to='IMAPS_app.supplier'),
        ),
        migrations.AddField(
            model_name='ingredientsrawmaterials',
            name='SupplierCode',
            field=models.ForeignKey(db_column='SupplierCode', on_delete=django.db.models.deletion.CASCADE, to='IMAPS_app.supplier'),
        ),
    ]
