# Generated by Django 5.1.6 on 2025-05-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMAPS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrawmaterials',
            name='Cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientsrawmaterials',
            name='QuantityBought',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredientsrawmaterials',
            name='QuantityLeft',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='packagingrawmaterials',
            name='Cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
