# Generated by Django 5.0.4 on 2025-05-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IMAPS_app", "0002_alter_ingredientsrawmaterials_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=64, verbose_name="Table")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("column", models.CharField(max_length=64, verbose_name="Column")),
                ("prev", models.TextField(blank=True, null=True, verbose_name="Prev")),
                ("new", models.TextField(blank=True, null=True, verbose_name="New")),
            ],
            options={
                "db_table": "change_log",
                "ordering": ["-date"],
            },
        ),
    ]
