# Generated by Django 5.1.6 on 2025-05-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMAPS_app', '0002_alter_ingredientsrawmaterials_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsrawmaterials',
            name='change_status',
            field=models.CharField(choices=[('active', 'Active'), ('old_modified', 'Old Modified'), ('new_modified', 'New Modified'), ('deleted', 'Deleted')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='packagingrawmaterials',
            name='change_status',
            field=models.CharField(choices=[('active', 'Active'), ('old_modified', 'Old Modified'), ('new_modified', 'New Modified'), ('deleted', 'Deleted')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='supplier',
            name='change_status',
            field=models.CharField(choices=[('active', 'Active'), ('old_modified', 'Old Modified'), ('new_modified', 'New Modified'), ('deleted', 'Deleted')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='usedingredient',
            name='change_status',
            field=models.CharField(choices=[('active', 'Active'), ('old_modified', 'Old Modified'), ('new_modified', 'New Modified'), ('deleted', 'Deleted')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='usedpackaging',
            name='change_status',
            field=models.CharField(choices=[('active', 'Active'), ('old_modified', 'Old Modified'), ('new_modified', 'New Modified'), ('deleted', 'Deleted')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='SupplierCode',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
