# Generated by Django 5.0.4 on 2025-05-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IMAPS_app", "0002_alter_ingredientsrawmaterials_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="change_status",
            field=models.CharField(
                choices=[("active", "Active"), ("deleted", "Deleted")],
                default="active",
                max_length=10,
            ),
        ),
    ]
