# Generated by Django 2.2.28 on 2025-05-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMAPS_app', '0004_auto_20250514_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='ContactNumber',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='EmailAddress',
            field=models.CharField(blank=True, default=' ', max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='PointPerson',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='SocialMedia',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
    ]
